# Generated by Django 3.1.4 on 2021-01-03 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id_cart', models.IntegerField(primary_key=True, serialize=False)),
                ('date_cart', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id_order', models.IntegerField(primary_key=True, serialize=False)),
                ('total_items', models.CharField(blank=True, max_length=120, null=True)),
                ('total_price', models.CharField(blank=True, max_length=60, null=True)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cartdetails')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id_shipping', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField(blank=True, max_length=120, null=True)),
                ('door_no', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=220, null=True)),
                ('city', models.CharField(blank=True, max_length=220, null=True)),
                ('pincode', models.CharField(blank=True, max_length=120, null=True)),
                ('id_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderdetails')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products'),
        ),
    ]
