# Generated by Django 3.1.4 on 2021-01-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210103_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetails',
            old_name='customer_id',
            new_name='id_customer',
        ),
        migrations.RenameField(
            model_name='cartdetails',
            old_name='product_id',
            new_name='id_product',
        ),
    ]
