# Generated by Django 3.1.5 on 2021-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210103_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='id_cart',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='id_order',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='id_shipping',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
